### ISSUE TITLE
Browse for specific file

### ISSUE THREAD

**Issue by JerryBinder** [JerryBinder/BackDatUp#20]
Description: Finds a file on the computer.
Actor: User.
Trigger: User enters file name in search bar on user interface.

Conditions:
Pre: The application must be open.
Post: The file must either be located or found to not exist in storage.

**Comment by JerryBinder** [comment]
JFileChooser is the best choice for this

https://docs.oracle.com/javase/7/docs/api/javax/swing/JFileChooser.html

**Comment by jb-schmidt** [comment]
I tested this in the main UI with JFileChooser, I can handle this as part of the UI easily.

**Comment by JerryBinder** [comment]
Sounds perfect! Thanks.
